import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Users } from "lucide-react";
function Nav(){return(<nav className="sticky top-0 z-50 bg-card/90 backdrop-blur-lg border-b border-border"><div className="container mx-auto flex items-center justify-between h-16 px-4"><Link to="/" className="flex items-center gap-2"><div className="w-9 h-9 rounded-xl gradient-primary flex items-center justify-center"><Users className="w-5 h-5 text-primary-foreground"/></div><span className="text-xl font-bold text-foreground">Samudaay</span></Link><Button variant="hero" size="sm" asChild><Link to="/register">Join Free</Link></Button></div></nav>);}
export default function PrivacyPolicy(){return(<div className="min-h-screen bg-background"><Nav/><div className="container mx-auto px-4 py-16 max-w-3xl"><h1 className="text-4xl font-bold text-foreground mb-2">Privacy Policy</h1><p className="text-muted-foreground mb-8">Last updated: March 22, 2026</p><div className="space-y-8 text-foreground">{[{h:"1. Information We Collect",p:"We collect information you provide directly to us, such as when you create an account, complete KYC, make an investment, or contact us for support. This includes: name, email address, phone number, PAN card number, Aadhaar number (masked), bank account details, and transaction history."},
{h:"2. How We Use Your Information",p:"We use the information we collect to: process investments and returns, verify your identity (KYC), communicate with you about your account, comply with legal and regulatory obligations under SEBI, PMLA, and Income Tax Act, and improve our platform."},
{h:"3. Data Security",p:"We implement industry-standard security measures including 256-bit SSL encryption, secure servers, access controls, and regular security audits. Your KYC documents are stored in encrypted form and are never shared with third parties except as required by law."},
{h:"4. Sharing of Information",p:"We do not sell your personal information. We may share data with: regulated service providers (payment processors, KYC verification agencies), government/regulatory bodies when legally required, and our internal team on a need-to-know basis."},
{h:"5. Data Retention",p:"We retain your data for as long as your account is active and for 7 years thereafter as required by financial regulations in India."},
{h:"6. Your Rights",p:"You have the right to access, correct, or delete your personal information (subject to legal obligations). You may contact our Grievance Officer at grievance@samudaay.com for any data-related requests."},
{h:"7. Cookies",p:"We use essential cookies to maintain your session and improve user experience. We do not use tracking cookies for advertising."},
{h:"8. Contact Us",p:"For privacy-related queries, contact: privacy@samudaay.com or write to Samudaay Technologies Pvt. Ltd., Andheri West, Mumbai – 400053."},
].map(s=>(<div key={s.h}><h2 className="text-xl font-bold mb-3">{s.h}</h2><p className="text-muted-foreground leading-relaxed">{s.p}</p></div>))}</div></div></div>);}
